---

- name: Installing Mesos | CentOS
  yum:
    name: "mesos"
    state: present

- name: Adding Zookeeper ID File | /etc/mesos/zk
  template:
    dest: /etc/mesos/zk
    src: zk.j2

- set_fact:
    total_zookeeper_count: 0

- set_fact:
    total_zookeeper_count: "{{ total_zookeeper_count |  int + 1 }}"
  with_items:
    - "{{ groups['zookeeper'] }}"

- name: Adding Zookeeper Qurum File | /etc/mesos-master/quorum
  template:
    dest: /etc/mesos-master/quorum
    src: quorum.j2

- name: Adding Hostname and IP
  lineinfile:
    dest: "{{ item }}"
    line: "{{ ansible_ssh_host }}"
    state: present
    create: true
  with_items:
    - /etc/mesos-master/hostname
    - /etc/mesos-master/ip

- name: Stoping Mesos | Slave
  service:
    name: mesos-slave
    state: stopped
    enabled: false

- name: Starting Mesos | Master
  service:
    name: mesos-master
    state: started
    enabled: true
